### PR TITLE
transform the pose to the correct frame

### PR DESCRIPTION
**Pull request by AngryTurtle2**
Hi! Thanks for developing such a great package!
But I find that the robot model will change its pose in the map when I use 2D pose Estimate.
So I want to change it.I define a function to change the pose message from the 2D pose estimate correctly.
Now I can first set the RVIZ fixed frame to be base_link or base_footprint,
then still using  2D pose estimate to publish the navigation goal,  with robot model no longer change its pose in the map because the model only change it when the fixed frame is the map.  Since the fixed frame is changed, So I need to  transform the Pose to the map frame.
finally change the fixed frame back to map.
I'm new in Github. If I did something wrong,I feel sorry for that.
And I feel sorry for my poor English.

### CODE REVIEW

**Comment by Combinacijus** [comment]
Can confirm it works.
Notes and things I implemented: 

- Transform to /map frame shouldn't be hardcoded for example in my case I wanted waypoints in utm frame (for gps navigation)
- I don't know about what maintainer thinks but in my opinion I don't think that `import traceback` is useful if everything is working correctly.
- Print statements are useful just for debugging
- Not sure what happens if already in correct frame so added extra check
- Changed function name (not sure which is better)

```
-  import traceback
-  waypoints.append(changePose(pose))
+  waypoints.append(tf_pose(pose, rospy.get_param('~goal_frame_id', 'map')))
```

```
# Transform Pose to the correct frame
def tf_pose(waypoint, to_frame):
    if waypoint.header.frame_id == to_frame:
        return waypoint  # Already in correct frame

    if not hasattr(tf_pose, 'listener'):
        tf_pose.listener = tf.TransformListener()
        
    tmp = PoseStamped()
    tmp.header.frame_id = waypoint.header.frame_id
    tmp.pose = waypoint.pose.pose
    try:
        tf_pose.listener.waitForTransform(to_frame, tmp.header.frame_id, rospy.Time(0), rospy.Duration(3.0))
        pose = tf_pose.listener.transformPose(to_frame, tmp)
        ret = PoseWithCovarianceStamped()
        ret.header.frame_id = to_frame
        ret.pose.pose = pose.pose
        return ret
    except:
        rospy.logwarn("CAN'T TRANSFORM POSE TO {} FRAME".format(to_frame))
        exit()
```

**Comment by AngryTurtle2** [comment]
@Combinacijus 
Hi! Thanks for your confirmation. 
I'm new in ROS and python,I tested the code and ran it successfully, but I didn't review the code.
I think your code is better than me. Thanks a lot.
* For the /map frame is hardcoded, I want to write code as soon as possible, so I  don't consider using it on other devices.
* For the traceback and print statement, I use them for debugging, and forget to remove it. Sorry for that.

Good wishes!

**Comment by danielsnider** [comment]
Thanks everyone! I will take a look at this in a few weeks. I'm sorry about the delay. If you can add any unit tests or functional in the meantime, that would help get this merged sooner. 
Again, much appreciated.

**Comment by danielsnider** [comment]
Hi @AngryTurtle2, nice work. I will merge your code into master you can please commit the updates that @Combinacijus has kindly provided. Test it once more and let me know please.

**Comment by AngryTurtle2** [comment]
Hi! @danielsnider I already updates and commit the codes provided by @Combinacijus . And test it with turtlebot3 burger in gazebo simulation.Please check it ! Thanks.

**Comment by danielsnider** [comment]
Thanks all 👍

**Pull request merged**
